spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: #
    password: #
    url: jdbc:postgresql://localhost:5432/jwt
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
